lib/compilers/babel-compiler.js
let babel use the built-in babel preset instead of looking for it in current working directory (may not exist).
=> Use the absolute path to babel preset

lib/process.js, test/FunctionalSFC.spec.js, test/resources/FunctionalSFC.vue
Vue supports Pure Functional templates from version 2.5:
https://vue-loader.vuejs.org/en/features/functional.html
With this pull request jest-vue would allow them to be tested.
* Note that we need to nest props attribute in propsData like this:
```
const wrapper = shallow(FunctionalSFC, {
propsData: { props: { msg: 'Hello' }}
})
```
=> Process functional single file components

lib/process-functional.js, lib/process.js, test/FunctionalSFC.spec.js, test/FunctionalSFCParent.spec.js, test/process-functional.spec.js, test/resources/FunctionalSFC.vue, test/resources/FunctionalSFCParent.vue
The previous solution caused problems when a functional SFC was used inside a parent component.
The problem is fixed as you can see in test _FunctionalSFCParent.spec_
And now you can test functional props with propsData like any other common component as seen in _FunctionalSFC.spec.js_:
`  const wrapper = shallow(FunctionalSFC, {
propsData: { msg: 'Hello' }
})`
=> Generate appropriate prop definitions for functional SFCs

README.md, lib/compilers/haml-compiler.js, lib/template-compiler.js, package-lock.json, package.json
Hi!
In a recent project I'm involved to use [Haml.js](https://github.com/tj/haml.js) as templating preprocessor for my `*.vue` files.
Here's a PR that enable support for it to pass the rendered template content to Jest.
Thanks.
=> Add support for haml preprocessor

lib/process.js, test/Babel.spec.js, test/resources/BasicSrc.html, test/resources/BasicSrc.js, test/resources/BasicSrc.vue
Close #28
Not sure it's ready to merge as there are probably some implications in sourcemaps generation.
=> feat(src): Add support of template and script src tags

lib/compilers/coffee-compiler.js, package-lock.json, package.json
coffee-script is deprecated. They recommend using coffeescipt instead.
Please see npm:
https://www.npmjs.com/package/coffee-script
Please also see this commit: https://github.com/jashkenas/coffeescript/commit/8ec10fa8ce9138db220844af31d9826660660513
Thanks,
=> deprecated: replace coffee-script with coffeescript

lib/compilers/babel-compiler.js, lib/compilers/coffee-compiler.js, lib/load-babel-config.js, test/coffee.spec.js, test/load-babel-config.spec.js, test/resources/CoffeeES6.vue, test/resources/CoffeeScriptES6.vue
`coffeescript` can adopt babel as a transpiler. `transpile` is the way how they set transpiler.
Please see http://coffeescript.org/#transpilation
This allows you to have vue files which adopt coffee/coffeescript (ES6) as `lang`.
I added tests and vue files.
=> Transpile coffeescript written in ES6

lib/compilers/babel-compiler.js, lib/load-babel-config.js, package-lock.json, package.json, test/Babel.spec.js, test/load-babel-config.spec.js
This makes `babel-core` a peer dep so that it can use whatever version of `babel-core` the user specifies.
Also removes the default `babel-preset-vue-app` configuration - I don't think it's a good idea to hard code that in here, especially when we are going to ship a new preset with vue-cli 3.0. If the user doesn't have a `.babelrc`, vue-jest should just skip babel.
=> Fix Babel 7 compat

lib/process.js, test/relative/resource.styl, test/resources/StylusRelative.vue, test/stylus.spec.js
=> Fix issue parsing relative imports in stylus files

lib/process.js, test/NamedExport.spec.js, test/resources/NamedExport.vue
We encountered some problems while using named exports in Vue components.
While it seems to work well in the vue-loader context, vue-jest seems to just discard named exports.
This pull request fixes this behavior.
=> Fixes export to include named exports (including test)

lib/process.js, test/less.spec.js, test/postcss.spec.js, test/resources/Less.vue, test/resources/PostCss.vue
Other than Sass/SCSS, we may face parsing errors with `cssExtract.extractClasses(cssCode);` in `processStyle (stylePart, filePath)` if you give code which is invalid as pure CSS. `css` module can't parse.
like 
```css
.testPostcCSS {
body {
@media screen {
background-color: red;
}
}
}
```
This syntax is allowed for almost CSS preprocessors. Anyway, some other syntaxes may make an exception with `css` module. So, I just added exts to ignore compilation.
=> Avoid parsing LESS, PostCSS too

README.md
It's no longer needed - Jest handles it by default.
See https://github.com/facebook/jest/pull/5177
=> mapCoverage removed from Jest

lib/compilers/typescript-compiler.js, test/TypeScript.spec.js
related: https://github.com/vuejs/vue-jest/issues/60
thank you for creating an awesome repository.
i have same the issue, so i send the this PR to fix it.
=> use empty string when sourceMapText is undefined

lib/process.js, test/less.spec.js, test/postcss.spec.js, test/resources/LessModule.vue, test/resources/PostCssModule.vue, test/resources/SassModule.vue, test/scss.spec.js
related: https://github.com/vuejs/vue-jest/issues/63
i also want to use sass module, so fix it.
=> suppress the error when using sass, postcss, less module

README.md, lib/compilers/pug-compiler.js, lib/process.js, lib/template-compiler.js, test/pug.spec.js, test/resources/PugBase.pug, test/resources/PugExtends.vue
Hi!
We have a set of reusable Vue components that share a lot of functionality and also some features within the template. Since Vue doesn't seem to have a clear way of extending templates, I'm using Pug to define a base template and include it into the child templates (a similar way to how it's done in this [article](https://medium.com/js-dojo/extending-vuejs-components-42fefefc688b)).
All works well and nicely with our Webpack build, but those changes broke our tests. I traced the problem into vue-jest and the fact that there is no way to give the Pug compiler any configuration options. When one is using e.g. absolute paths, Pug requires a 'basedir' attribute to be given, otherwise it will complain and refuse to compile anything.
So, here's a PR that implements support for configuring …
=> feat: configuring Pug compiler from vue-jest configuration

lib/compilers/pug-compiler.js, lib/process.js, lib/template-compiler.js, test/pug.spec.js, test/relative/PugRelativeBase.pug, test/resources/PugRelativeExtends.vue
Here's another. When extending a Pug template from a relative path, Pug compiler requires a filename attribute to be given in the compile() method options.
```
<template lang="pug">
extends ../relative/PugRelativeBase.pug
block component
div(class="pug-extended")
</template>
...
pug.compile(templateData, { filename: '/home/user/my/coolest/template/ever.pug' })
```
Apparently the filename has to be the full path to the file being compiled, which is something that can't be achieved via Jest configuration since it's common to all tests. But as the full path of the file being processed is available in the template compiler, it's easy to pass it to the Pug compiler in order to make extending from relative paths work correctly.
=> feat: Support for extending pug templates using relative paths

README.md, lib/compilers/babel-compiler.js, lib/compilers/coffee-compiler.js, lib/compilers/typescript-compiler.js, lib/load-babel-config.js, lib/load-typescript-config.js, lib/process.js, test/load-babel-config.spec.js, test/load-typescript-config.spec.js
This adds the capability to specify configurations for both babel and typescript in the Jest globals config.
Supercedes #53
=> Global config options for Babel and Typescript

lib/process.js, test/resources/SassModuleFunctional.vue, test/resources/ScssModuleFunctional.vue, test/sass.spec.js, test/scss.spec.js
This PR should fix vue-jest's behavior concerning style injection with modules on functional components.
Edit: We've added this branch to a current project and tested it's fixes together with a lot of functional components.
=> feat: Adds style injection for modules in functional components.

package.json, test/FunctionalSFC.spec.js, test/FunctionalSFCParent.spec.js, test/NoScript.spec.js, test/RenderFunction.spec.js, test/TypeScript.spec.js, test/coffee.spec.js, test/css.spec.js, test/jade.spec.js, test/less.spec.js, test/postcss.spec.js, test/pug.spec.js, test/sass.spec.js, test/scss.spec.js, test/stylus.spec.js
=> fix: update to support new @vue/test-utils

lib/compilers/babel-compiler.js, lib/compilers/coffee-compiler.js, lib/compilers/typescript-compiler.js, lib/load-babel-config.js, lib/process.js, test/Babel.spec.js, test/load-babel-config.spec.js
Now searches with a depth of infinity from the file path, as described
in #66.
For my personal use, just switching the depth from 0 to the default (INFINITY) was enough; but as per the ticket I try to use the filePath now as well.
=> Improve .babelrc lookup

lib/deprecate.js, test/deprecate.spec.js
Prerequisite for #111 (deprecating `babelRcFile`, `tsConfigFile`)
=> feat: add deprecation message lib

README.md, lib/load-babel-config.js, lib/load-typescript-config.js, test/load-babel-config.spec.js, test/load-typescript-config.spec.js
=> feat: update to support babelConfig and tsConfig

lib/process.js, test/resources/SourceMapsSrc.vue, test/sourceMaps.spec.js
Hello. This PR fixes the issue when Idea IDE uses *.vue file instead of script file included with <script src=""
Chrome Dev Tools still works well. Would be nice if someone can confirm that VSCode works correct as well
=> use correct source map names for script files imported over src

lib/load-babel-config.js, test/load-babel-config.spec.js
=> Consider the value of the babelConfig config property before checking for the babel.config.js file

lib/index.js
Upgrade to vue-jest to 4.0.0-beta failed since `babel-jest` introduced `config` in `getCacheKey` https://github.com/facebook/jest/blob/master/packages/babel-jest/src/index.js#L53
@eddyerburgh Could you give me a review and trigger a new release ?
=> fix: add mssing argument in getCacheKey

e2e/__projects__/custom-transformers/babel-transformer.js, e2e/__projects__/custom-transformers/babel.config.js, e2e/__projects__/custom-transformers/package.json, lib/process-style.js, lib/process.js, lib/typescript-transformer.js, lib/utils.js, package.json
This PR enables the use of custom script transformers, resolves extends property from tsconfig.json.
Similar to custom CSS transformers this help when we have any custom processing to the script(ts/js/coffee).
For eg. When users do not have babel.config.js at the root of the application but have it at a specific location, we can create a custom babel-transformer by passing in babel-jest's `createTransformer(babelConfig)`  with the config pointing to the babel configuration.
Fixes, #148, #144
=> let the script processer pick custom transformers when present

e2e/__projects__/style/components/External.vue, e2e/__projects__/style/components/styles/external.css, e2e/__projects__/style/test.js, lib/process-style.js, lib/process.js, lib/utils.js
This addresses use of external css files for components as described here: https://github.com/vuejs/vue-jest/issues/76
@eddyerburgh not sure how you feel about just writing the external file into `stylePart` but it seemed like the easiest way of doing this.
=> External css

lib/index.js, lib/utils.js
- Remove ts-jest imports from root of files
This is a stop gap PR to remove ts-jest imports, which throws an error if typescript isn't installed.
In the future we will remove ts-jest entirely
=> fix: remove typescript dep

package.json, yarn.lock
Used in lib/process.js but not listed in dependencies or peer dependencies.
https://github.com/vuejs/vue-jest/blob/d6f4b716d77bf8a69c1f75abf52a286d4984d356/lib/process.js#L15
Fixes #172
=> chore: add convert-source-map

.circleci/config.yml
This will allow us to install some dependencies that require node > 8
=> deps: updating circleci to run on node 10

package.json, yarn.lock
`source-map` was accidentally removed in here https://github.com/vuejs/vue-jest/commit/d6c4e475e5498083b6273d73e641a1e3f086d087#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L75
but we need it https://github.com/vuejs/vue-jest/blob/0b0d5e2dcd28da728bc0928efdfa6817df6113e7/lib/generate-source-map.js#L2
=> chore: add dep

package.json, yarn.lock
Fix CI tests. They changed their lib - it's promised based now. For now, using the old versions fixes it. We should upgrade sometime.
=> fix: pin source-map version

e2e/__projects__/basic/components/FunctionalSFCRender.vue, e2e/__projects__/basic/test.js, lib/process.js
Before this PR, a component like the next one would fail to be tested because `$style` would be `undefined`:
```js
<script>
export default {
name: 'FunctionalSFCRender',
functional: true,
render(createElement, { $style }) {
return createElement('div', {
class: [$style.ModuleClass]
})
}
}
</script>
<style lang="scss" module>
.ModuleClass {
width: auto;
}
</style>
```
The reason for being a failure is related to a missing `<template>` block, however, a functional component can work properly using `functional: true` and a `render` function. Now it tries to find `functional: true` using a regex. 
This PR also includes a simple test that uses to fail without these changes.
=> Support pure functional components

README.md, package.json, yarn.lock
Jest 25 is released https://jestjs.io/blog/2020/01/21/jest-25.
=> Support Jest 25

lib/utils.js
This prevents `const vue_1 = require('vue')` from conflicting, since it will do `var vue_1` instead.
This feels pretty bad, I don't know the correct solution. 🤔
=> Force ES5 for TS compilation

README.md
The readme doc incorrectly states that if you are using versions lower than 24.0.0 of Jest you should use the babel-core@bridge package. This should be versions _greater_ than 24.0.0
I spent a long time banging my head against the wall over this.
=> Update incorrect Babel 7 instruction in README.md

lib/utils.js, package.json, yarn.lock
The typescript object was not defined on the result of the configsFor(config) in our project.
On inspection we found that parsedTsConfig and _parsedTsConfig of the configsFor result had the correct object.
Using:
- ts-jest: 26.1.0
- babel-jest: 26.0.1
- vue-jest: 4.0.0-beta.3
in the jest.config.js we have defined the globals as 
gloabls: {
'ts-jest': {
babelConfig: true,
tsConfig: 'tsconfig.jest.json',
},
'vue-jest': {
babelConfig: true,
tsConfig: 'tsconfig.jest.json',
},
}
=> Update ts-jest version and api

e2e/__projects__/style/components/Scss.vue, e2e/__projects__/style/package.json, e2e/__projects__/style/setup.js, e2e/test-runner.js, lib/module-name-mapper-helper.js
Sass supports importing partials with or without the leading underscore:
https://sass-lang.com/documentation/at-rules/import#partials
Because `applyModuleNameMapper()` uses `require.resolve()` to employ node module resolution on a bare import, it would throw an exception if the import elided the leading `_` from the basename. For example:
```html
<style lang="scss">
@import "~foo/bar"; // Actual filepath might be `node_modules/foo/_bar.scss`.
</style>
```
Writing the test for this was a bit tricky, so I had to make some changes to the test runner. Node module resolution only ever uses realpaths, so when `module-name-mapper-helper.js` makes calls to `require.resolve()`, node won't be looking in the test directory's `node_modules`. As an aside, can we rename `module-name-mapper-helper.js` …
=> fix: Sass partials imports from node_modules

README.md, e2e/__projects__/style/components/Scss.vue, e2e/__projects__/style/package.json, e2e/__projects__/style/setup.js, lib/module-name-mapper-helper.js
As discovered in https://github.com/vuejs/vue-jest/pull/256#issuecomment-664764912.
When importing a Sass file that has dots in its filename but without the `.scss` extension (e.g. `@import 'foo.bar';`), our resolver would assume `.bar` was the extension and forego appending `.scss`, causing `require.resolve()` to throw an exception.
We need to look for `.scss`, `.sass`, and `.css` extensions, as all of these are possible. Previously, it would automatically assume the extension for the file was the same as the `lang` attribute set on the `<style>` block, but Sass has no problems importing `.sass` from a `.scss` file or vice-versa, and `.css` is also very common.
=> Fix bare imports of Sass files with dots.in.filename.scss

e2e/__projects__/basic/__snapshots__/test.js.snap, lib/generate-code.js, lib/process.js
The new `@vue/compiler-sfc` generates code using ES module syntax. It is causing some problems with vue-cli: https://github.com/vuejs/vue-cli/issues/5714#issuecomment-665471088
Easy fix is just use babel to compile the template code to commonjs module syntax. The idea for v5 was to be entirely `ts-jest` based, although even if I set `target: es5` etc in `tsconfig.json` I could not get it to work. This seems like the best solution, so people can use VTU and vue-jest with vue-cli out of the box.
I tested this in a pretty primitive manner: create a new cli project:
```
Vue CLI v4.5.0
? Please pick a preset: Manually select features
? Check the features needed for your project: Choose Vue version, Babel, TS, Unit
? Choose a version of Vue.js that you want to start the project with 3.x …
```
=> Transpile template using babel

package.json
It is mainly because ts-jest has a hard-coded jest version requirement.
And ts-jest is listed as optional because not every project needs it.
=> refactor!: support wider range of jest versions by making babel-jest & ts-jest peer dependencies

e2e/__projects__/basic/__snapshots__/test.js.snap, e2e/__projects__/basic/test.js, lib/process.js, package.json
Resolve #241 and facebook/jest#10089
In `jest@25.5.0` or later, coverage reporter creates an inline source-map from `map` property. (facebook/jest#9811)
But `vue-jest` already adds inline source-map with [process()](https://github.com/vuejs/vue-jest/blob/d207d06f5c55ec046367efe16f1e08e40381af57/lib/process.js#L138).
So reporter throws error due to duplicate source maps.
This PR avoids duplicates by removing ~~map property~~ inline source map.
=> [BREAKING CHANGE] remove inline source-map on process() output

e2e/__projects__/basic/__snapshots__/test.js.snap, lib/process.js
Seems to fix https://github.com/vuejs/vue-cli/issues/5714. Tested locally with latest vue-cli with a TS + babel and no babel setup.
=> Use transpileModule for TS and transform for babel conditionally

README.md
`process()` sample in README is different from the [implementation](https://github.com/vuejs/vue-jest/blob/master/lib/process-custom-blocks.js#L11).
This PR fixes it.
=> docs: fix custom-block processor sample

e2e/__projects__/babel-in-package/package.json, e2e/__projects__/basic/package.json, e2e/__projects__/basic/test.js, e2e/__projects__/custom-transformers/package.json, e2e/__projects__/style/package.json, e2e/__projects__/style/test.js, package.json, yarn.lock
- bump `@vue/test-utils` from `1.0.0-beta.28` to `1.0.3`
- replace deprecated assert functions
- [Wrapper.contains()](https://vue-test-utils.vuejs.org/api/wrapper/#contains)
- [Wrapper.is()](https://vue-test-utils.vuejs.org/api/wrapper/#is)
=> chore: bump @vue/test-utils to release version in /e2e

lib/process.js
Jest requires a `map` property of type `RawSourceMap`, but this package passes `SourceMapGenerator`.
I forgot to fix this in #255, excuse me. 
fixes #241 and facebook/jest#10089
=> fix: convert SourceMapGenerator to RawSourceMap

package.json, yarn.lock
Release 4.0.0-rc.0 which includes the fix for https://github.com/vuejs/vue-jest/issues/241
Also bump `jest` and `ts-jest` versions to 26.x
=> release 4-rc.0 and update jest and ts-jest to 26.x

package.json
Windows PowerShell does not support single-quoted arguments.
This repo hooks npm script on commit, so we cannot develop in windows environment.
This PR changes args to double-quoted, and changes `npm run` command to `yarn`.
=> fix: change single-quote to double-quote in npm-scripts

e2e/__projects__/basic/components/TemplateString.vue, e2e/__projects__/basic/package.json, e2e/__projects__/basic/test.js, lib/process.js
Fixes #98.
This PR is adding to the `vue-jest` possibility to configure the template compiler used by [`@vue/component-compiler-utils` package](https://www.npmjs.com/package/@vue/component-compiler-utils).
By passing correct configuration to the template compiler we can mitigate issues like the #98 - where the problem is directly connected with the proper tool configuration (in this case - the [`buble` library](https://www.npmjs.com/package/buble)).
BTW. the graphql case was added in this PR as an e2e test.
The problem can be reproduced by checking out the first commit in this PR and running `yarn test`. Then you'll see this error in the console:
```bash
FAIL ./test.js
● Test suite failed to run
Tagged template strings are not supported. Use `transforms: { templateString: false }` to skip …
```
=> feat: add compile template options

e2e/__projects__/style/components/External.vue, e2e/__projects__/style/test.js, lib/process-style.js
Follow up of #158 PR - external css files might use paths which needs `moduleNameMapper` resolution.
In case of the app I'm working on, we use external SCSS in a following way:
```html
<style lang="scss" src="@/assets/stylesheets/_bootstrap.module.scss" module="$styleBootstrap" />
```
`vue-jest` have failed in this case, because it always tried to load `style.src` as a relative path.
Now, the `moduleNameMapper` is used to resolve correct, absolute path before anything else happens.
Change have been tested - I think this one, simple test is enough to cover it, what do you think?
=> fix: external css files src resolution

e2e/__projects__/style/components/External.vue, e2e/__projects__/style/test.js, lib/process-style.js
`vue-jest` fails when using proper html5 syntax when including external css files.
When I import external CSS in a following way (that's something recommended by [vue-loader](https://vue-loader.vuejs.org/spec.html#src-imports) and only way handled properly by vetur - [they do not support highlighting of self-closing `style` tags](https://github.com/vuejs/vetur/issues/1792)):
```html
<style src="./_bootstrap.module.scss" module="$styleBootstrap"></style>
```
`vue-jest` fails - it treats this style block as there would be no `src` attribute at all!
Fixed that case (added `content.trim()` - that's because `vue/component-compiler` for `<style></style>` returns bunch of spaces - something like: "          ").
=> fix: external css properly handle html5-compliant syntax

e2e/__projects__/basic/components/ClassComponent.vue, e2e/__projects__/basic/package.json, e2e/__projects__/basic/test.js, e2e/__projects__/basic/yarn.lock, lib/generate-code.js, yarn.lock
=> Add support for class components

e2e/__projects__/basic/components/ScriptSetup.vue, e2e/__projects__/basic/package.json, e2e/__projects__/basic/yarn.lock, lib/process.js, package.json, yarn.lock
#304 (kind of).
This lets vue-jest work with the latest `<script setup>` as of Vue 3.0.3. There is still a problem in Test Utils, though: https://github.com/vuejs/vue-test-utils-next/issues/263
=> chore: bump to vue 3.0.3

e2e/__projects__/babel-in-package/package.json, e2e/__projects__/babel-in-package/yarn.lock, e2e/__projects__/basic/__snapshots__/test.js.snap, e2e/__projects__/basic/package.json, e2e/__projects__/basic/yarn.lock, lib/utils.js, package.json, yarn.lock
We can use the `tsconfig` module to see if a `tsconfig.json` exists. If it doesn't, we can assume they are not using TypeScript. This removes the need to install TS for non TS projects.
=> fix: do not require ts-jest and typescript

README.md, lib/process.js
In #288 PR, `transformAssetUrls` and `transpileOptions` are overwrote to `{}` if `vue-jest.templateCompiler` option is not provided. 
It fails test cases that depend on default TemplateCompileOptions.
This PR:
- Fallback default TemplateCompileOptions if user does not set it.
- Add Documentation of `templateCompiler` option
=> fix: add fallback to default TemplateCompileOptions

package.json, yarn.lock
`vue-jest` has a [dependency](https://github.com/vuejs/vue-jest/blob/next/lib/map-lines.js#L1) on `source-map` but it is not listed in the package.json. This can cause a resolution issue inside a repo with another package that uses `vue-jest` > 0.7 since there was a [breaking change](https://github.com/mozilla/source-map/blob/master/CHANGELOG.md#070).
=> add source map dependency (next)

e2e/__projects__/basic/components/TsSrc.ts, e2e/__projects__/basic/components/TsSrc.vue, e2e/__projects__/basic/test.js, lib/transformers/typescript.js
This was based on #330 but applied to Vue3.
This properly generates the coverage reports with the filename TsSrc.ts instead of module.ts
```
-   module.ts               |       75 |      100 |    66.67 |       75 |                20 |
+   TsSrc.ts                |       75 |      100 |    66.67 |       75 |                20 |
```
=> Fix coverage reports for typescript for vue3

e2e/__projects__/basic/components/ClassComponentProperty.vue, e2e/__projects__/basic/components/ClassComponentWithMixin.vue, e2e/__projects__/basic/components/ClassMixin.ts, e2e/__projects__/basic/package.json, e2e/__projects__/basic/test.js, lib/generate-code.js
Fix for using class component with mixins and also for importing
Vue from vue-property-decorator instead of vue-class-component.
See for more details: https://github.com/vuejs/vue-test-utils-next/issues/544
=> Fix: support for class component mixins

e2e/__projects__/basic/components/FunctionalRenderFn.vue, e2e/__projects__/basic/test.js, lib/generate-code.js
I just commented out line `node.add(';exports.default = {...exports.default};')`, added simple test, and everything just works.
Perhaps, in some edge cases, you will still need to copy `exports.default` into yourself. Then you can try this option:
```js
node.add(`;
if (typeof exports.default === 'function') {
const fn = exports.default;
exports.default = (...args) => fn(...args);
Object.assign(exports.default, fn)
} else {
exports.default = {...exports.default};
}
`)
```
=> fix: process render function, exported as default #332

README.md
before this commit all css options appeared on one line
=> readme chore: Fix css options appearing all on one line

e2e/__projects__/basic/__snapshots__/test.js.snap, e2e/__projects__/style/components/External.vue, e2e/__projects__/style/components/Less.vue, e2e/__projects__/style/components/PostCss.vue, e2e/__projects__/style/components/Sass.vue, e2e/__projects__/style/components/Scss.vue, e2e/__projects__/style/components/Stylus.vue, e2e/__projects__/style/test.js, e2e/test-runner.js, lib/generate-code.js, lib/process-style.js, lib/process.js
#268 
I enabled to use cssModule in two way
- $style
- useCssModules
=> add css-module feature

e2e/__projects__/style/components/Less.vue, e2e/__projects__/style/components/styles/less-a.less, e2e/__projects__/style/test.js, lib/process-style.js
I'm sorry... this issue is related with CSS Modules...  🙇🏻 
#350 
We don't have `lang === less` condition in process styles, so I got that issue when I try to use import statement on less file.
=> add less relative import

e2e/__projects__/babel-in-package/package.json, e2e/__projects__/basic/package.json, e2e/__projects__/custom-transformers/package.json, e2e/__projects__/style/package.json
End-to-end test projects should be independent, but it depends on root `devDependencies` now.
This PR fixes there dependencies.
=> fix(deps): add missing devDependencies in e2e/ projects (for 4.x)

e2e/2.x/babel-in-package/package.json, e2e/2.x/basic/package.json, e2e/2.x/basic/test.js, e2e/2.x/custom-transformers/babel-transformer.js, e2e/2.x/custom-transformers/package.json, e2e/2.x/style/package.json, packages/vue2-jest/lib/index.js, packages/vue2-jest/lib/process-style.js, packages/vue2-jest/lib/process.js, packages/vue2-jest/lib/transformers/coffee.js, packages/vue2-jest/lib/transformers/typescript.js, packages/vue2-jest/lib/utils.js, packages/vue2-jest/package.json, yarn.lock
Followup, and quasi identical PR to #343 
@lmiller1990 if that looks good, it would be nice to have an alpha release. I think I need it to update the CLI to jest 27 (as it looks like I need to bump Vue 3 and Vue 2 projects at the same time)
=> feat: jest v27 support for vue2-jest

e2e/3.x/babel-in-package/package.json, e2e/3.x/basic/__snapshots__/test.js.snap, e2e/3.x/basic/components/ScriptSetupSugarRef.vue, e2e/3.x/basic/package.json, e2e/3.x/basic/test.js, e2e/3.x/custom-transformers/package.json, e2e/3.x/javascript/package.json, e2e/3.x/style/package.json, e2e/3.x/typescript-with-babel/package.json, e2e/3.x/typescript/package.json, packages/vue3-jest/lib/process.js, packages/vue3-jest/package.json, yarn.lock
This PR allows testing components using sugar ref take 2 https://github.com/vuejs/rfcs/discussions/369
Note that I did not make it configurable for now, but maybe it should be. Opinions?
=> feat: enable sugar ref take 2 for vue3-jest

packages/vue3-jest/lib/process.js
This PR allows to pass down compilerOptions to vue-jest transformation.
=> feat: add compilerOptions to vue-jest global options

README.md
I'm not entirely sure I got the current situation right – please feel free to suggest any addition or modification!
=> docs: Add installation for each vue/jest version combination

e2e/3.x/babel-in-package/package.json, e2e/3.x/basic/package.json, e2e/3.x/custom-transformers/package.json, e2e/3.x/javascript/package.json, e2e/3.x/style/package.json, e2e/3.x/typescript-with-babel/package.json, e2e/3.x/typescript/package.json, packages/vue3-jest/package.json, yarn.lock
Bumps vue-next version for an upcoming PR.
=> chore: bump to vue-next v3.2.19

README.md
Closes #406 
Specifying the version number makes the installation fail. 
Omitting the version number results in installing the correct alpha version.
=> Change: Remove Jest 27 version specification

e2e/3.x/babel-in-package/package.json, e2e/3.x/basic/package.json, e2e/3.x/custom-transformers/package.json, e2e/3.x/javascript/package.json, e2e/3.x/style/package.json, e2e/3.x/typescript-with-babel/package.json, e2e/3.x/typescript/package.json, packages/vue3-jest/package.json, yarn.lock
Note that this also removes the now unneeded `@vue/compiler-sfc` dependency.
Fixes #410
=> chore: update to vue v3.2.22

README.md, e2e/3.x/babel-in-package/package.json, e2e/3.x/basic/package.json, e2e/3.x/custom-transformers/package.json, e2e/3.x/javascript/package.json, e2e/3.x/style/package.json, e2e/3.x/typescript-with-babel/package.json, e2e/3.x/typescript-with-compiler-options/package.json, e2e/3.x/typescript-with-compiler-options/src/components/PropsDestructureTransform.vue, e2e/3.x/typescript-with-compiler-options/src/shims-vue.d.ts, e2e/3.x/typescript-with-compiler-options/src/test.ts, e2e/3.x/typescript-with-compiler-options/tsconfig.json, e2e/3.x/typescript/package.json, packages/vue3-jest/lib/process.js, packages/vue3-jest/package.json, yarn.lock
These options can be used to define Vue compiler options in `@vue/vue3-jest`.
For example, to enable the newly introduced `propsDestructureTransform` in Vue v3.2.20:
```js
globals: {
'vue-jest': {
compilerOptions: {
propsDestructureTransform: true
}
}
}
```
or to disable `refTransform` (which is enabled by default):
```js
globals: {
'vue-jest': {
compilerOptions: {
refTransform: false
}
}
}
```
=> feat: allow to pass compilerOptions via the Jest config for Vue 3

e2e/3.x/custom-block/__snapshots__/test.js.snap, e2e/3.x/custom-block/babel.config.js, e2e/3.x/custom-block/components/Basic.vue, e2e/3.x/custom-block/components/Multiple.vue, e2e/3.x/custom-block/package.json, e2e/3.x/custom-block/test.js, e2e/3.x/custom-block/transformer.js, packages/vue3-jest/lib/constants.js, packages/vue3-jest/lib/generate-code.js, packages/vue3-jest/lib/process-custom-blocks.js, packages/vue3-jest/lib/process.js
~~This is WIP pull request.~~
As the title, I’ll support be transforming custom blocks for Vue 3.
At this time, only jest 26.x is supported.
=> feat: support custom blocks for Vue 3

packages/vue3-jest/lib/utils.js
interop custom transformer require. Some transformers may not interop correctly when requiring, return `transformer.default` or `transformer`.
@vue/vue2-jest fix: #390
fixes #383
=> fix(vue3-jest): interop custom transformer require

e2e/2.x/style/colors.less, e2e/2.x/style/colors.scss, e2e/2.x/style/variables.less, e2e/2.x/style/variables.scss, packages/vue2-jest/lib/process-style.js
Closes #374
Fix importing relative paths inside a stylesheet being made globally available using the option `jest.globals['vue-jest'].resources`:
```json
{
"jest": {
"globals": {
"vue-jest": {
"resources": {
"scss": [
"./src/styles/settings/global.scss"
]
}
}
}
}
}
```
**src/styles/settings/global.scss**
```scss
@import './unit.scss';
$another-variable: 10px;
```
considering that _src/styles/settings/unit.scss_ exists, it shouldn't throw the following error
My branch is based on the `v4.0.1` tag which is the version I'm using. It doesn't seem like there is a `v4` branch I could base my PR on.
=> fix: allow importing relative paths in global resources

packages/vue3-jest/lib/utils.js
When the tsconfig path is not the default, I need to manually pass in the tsconfig path.Some configurations are shown below：
```ts
export default {
globals: {
'ts-jest': {
tsconfig: require.resolve('./tsconfig.jest.json'),
},
'vue-jest': {
tsConfig: require.resolve('./tsconfig.jest.json'),
},
},
}
```
The [tsconfig#resolveSync](https://github.com/TypeStrong/tsconfig/blob/master/src/tsconfig.ts#L49) method is called in the code to get the configuration. However, the configuration can't be obtained due to incorrect parameter passing, so it is compiled as JS code, resulting in compilation errors
=> fix(vue3-jest): compilation error while passing tsconfig path

README.md, e2e/2.x/babel-in-package/package.json, e2e/2.x/basic/package.json, e2e/2.x/custom-transformers/package.json, e2e/2.x/style/package.json, e2e/3.x/babel-in-package/package.json, e2e/3.x/basic/package.json, e2e/3.x/custom-block/package.json, e2e/3.x/custom-transformers/package.json, e2e/3.x/javascript/package.json, e2e/3.x/style/package.json, e2e/3.x/typescript-with-babel/package.json, e2e/3.x/typescript-with-compiler-options/package.json, e2e/3.x/typescript/package.json, packages/vue2-jest/package.json, packages/vue3-jest/package.json
Jest 28 is not the main version on npm, so we will follow suit and make vue2-jest@28 and vue2-jest@28 the main version, too.
You can still get the Jest 27 version with `yarn add vue3-jest@27`.
=> chore: release Jest 28 support

e2e/2.x/sass-importer/entry/babel-transformer.js, e2e/2.x/sass-importer/entry/components/Entry.vue, e2e/2.x/sass-importer/entry/package.json, e2e/2.x/sass-importer/entry/test.js, e2e/2.x/sass-importer/lib/index.vue, e2e/2.x/sass-importer/lib/package.json, e2e/2.x/sass-importer/sass-lib-v1/index.scss, e2e/2.x/sass-importer/sass-lib-v1/package.json, e2e/2.x/sass-importer/sass-lib-v2/index.scss, e2e/2.x/sass-importer/sass-lib-v2/package.json, e2e/3.x/sass-importer/entry/babel-transformer.js, e2e/3.x/sass-importer/entry/components/Entry.vue, e2e/3.x/sass-importer/entry/package.json, e2e/3.x/sass-importer/entry/test.js, e2e/3.x/sass-importer/lib/index.vue, e2e/3.x/sass-importer/lib/package.json, e2e/3.x/sass-importer/sass-lib-v1/index.scss, e2e/3.x/sass-importer/sass-lib-v1/package.json, e2e/3.x/sass-importer/sass-lib-v2/index.scss, e2e/3.x/sass-importer/sass-lib-v2/package.json, package.json, packages/vue2-jest/lib/module-name-mapper-helper.js, packages/vue3-jest/lib/module-name-mapper-helper.js, yarn.lock
Currently Sass imports that use the module import syntax (eg. `~module-to-import/some.sass`) are resolved relative to the vue-jest package. If you only have one version of that package, and everything has been hoisted to the same level as vue-jest (or higher), then things work as expected.
Where things start to fail is when you have more than one instance of the sass package you are trying to import as it is possible the wrong version will be loaded, and it is concievable that the file won't be found.
Where I encountered this problem, we had something like the following:
```
node_modules/
component-library/
node_modules/
sass-library@3.0.0
mixins.sass
some-component.vue:
<style lang="sass">
@import '~sass-library/mixins.scss';
.foo {
@use someMixinFromV3
}
</style>
sass-library@1.0.0 …
```
=> fix(sass-imports): resolve module imports relative to file being processed

e2e/2.x/babel-in-package/package.json, e2e/2.x/basic/package.json, e2e/3.x/babel-in-package/package.json, e2e/3.x/basic/package.json, e2e/3.x/typescript-with-babel/package.json, e2e/3.x/typescript-with-compiler-options/package.json, e2e/3.x/typescript/package.json, packages/vue2-jest/lib/transformers/typescript.js, packages/vue2-jest/lib/utils.js, packages/vue2-jest/package.json, packages/vue3-jest/lib/process.js, packages/vue3-jest/lib/transformers/typescript.js, packages/vue3-jest/lib/utils.js, packages/vue3-jest/package.json
**:warning:This PR contains BREAKING CHANGES!!:warning:**
This PR conflicts with #468, so I set as draft.
Resolve #171, #431
- Use `tsconfig` package to load TypeScript config.
- Remove `ts-jest` peerDependencies.
- Some tests will break that depend on `ts-jest` config.
```javascript
// jest.config.js
module.exports = {
globals: {
"ts-jest": {...} // Not loaded during transforming Vue (use tsconfig.json instead)
}
}
```
=> feat: load TypeScript config from `tsconfig` package instead of `ts-jest`

e2e/3.x/basic/__snapshots__/test.js.snap, packages/vue3-jest/lib/process.js
**:warning:This PR contains BREAKING CHANGES!!:warning:**
In `@vue/vue3-jest`, `getTypeScriptConfig` calls every times whether project uses TypeScript or not.
With that, js users will get unnecessary "Not found tsconfig.json" warnings.
Fix #490 
- Restrict calling `getTypeScriptConfig` function to when using `<script lang="ts">`, `<script lang="tsx">`, or `<script lang="typescript">`.
- Even if there is a `tsconfig.json` file in project, TypeScript will not transpile if `lang=ts` is not specified
|script|`tsconfig.json`|transpile|
|------|---------------|----------|
|JavaScript|No|`@babel/preset-env`|
|TypeScript|No|`@babel/preset-env` (with "Not found tsconfig.json" warning)|
|JavaScript|Yes|`typescript` -> `@babel/preset-env`|
|TypeScript|Yes|`typescript`|
=> fix(vue3-jest): reduce `getTypeScriptConfig` calls

e2e/2.x/babel-in-package/package.json, e2e/2.x/basic/__snapshots__/test.js.snap, e2e/2.x/basic/components/ScriptSetup.vue, e2e/2.x/basic/package.json, e2e/2.x/basic/test.js, e2e/2.x/custom-transformers/package.json, e2e/2.x/sass-importer/entry/package.json, e2e/2.x/sass-importer/lib/package.json, e2e/2.x/style/package.json, packages/vue2-jest/lib/generate-code.js, packages/vue2-jest/lib/map-lines.js, packages/vue2-jest/lib/process-custom-blocks.js, packages/vue2-jest/lib/process.js, packages/vue2-jest/package.json, yarn.lock
This PR basically borrows @FelixGraf work in #483 and merges snapshot fixes from #486 into it.
The source map in script setup generated code didn’t have a trailing `\n`, so the `__options__` var declaration was being inlined with it.
I removed the source map from the generated Vue 2 code, I don’t know if this is a necessary change, and someone with more insight on the library might shed some light.
=> feat: support <script setup> in Vue 2.7 (supersedes #483)

e2e/2.x/custom-block/__snapshots__/test.js.snap, e2e/2.x/custom-block/babel.config.js, e2e/2.x/custom-block/components/Basic.vue, e2e/2.x/custom-block/components/Multiple.vue, e2e/2.x/custom-block/package.json, e2e/2.x/custom-block/test.js, e2e/2.x/custom-block/transformer.js, e2e/2.x/custom-transformers/components/Scss.vue, packages/vue2-jest/lib/process-custom-blocks.js, packages/vue2-jest/lib/process.js
As mentioned in https://github.com/vuejs/vue-jest/pull/489#discussion_r977386910, vue2-jest v29.1.0 broke custom block processors.
This PR just reverts a few changes of #489, which look unrelated to the PR and are entirely broken. There seemed to be a `componentNamespace` config option added - but this was documented nowhere and the default value for it was broken.
=> fix: Revert vueOptionsNamespace changes from <script setup> commit

e2e/2.x/basic/components/ExtendedTsConfig.vue, e2e/2.x/basic/components/ModuleRequiringEsModuleInterop.js, e2e/2.x/basic/test.js, e2e/2.x/basic/tsconfig.base.json, e2e/2.x/basic/tsconfig.json, e2e/3.x/basic/components/ExtendedTsConfig.vue, e2e/3.x/basic/components/ModuleRequiringEsModuleInterop.js, e2e/3.x/basic/test.js, e2e/3.x/basic/tsconfig.base.json, e2e/3.x/basic/tsconfig.json, packages/vue2-jest/lib/ensure-require.js, packages/vue2-jest/lib/throw-error.js, packages/vue2-jest/lib/utils.js, packages/vue3-jest/lib/ensure-require.js, packages/vue3-jest/lib/throw-error.js, packages/vue3-jest/lib/utils.js
A change introduced in v28.1.0 in PR #471 unintentionally changed the behavior of the tsconfig parsing such that configs using "extends" were no longer being considered.
Fixes: #495
=> fix(tsconfig): parse extended tsconfigs when transpiling script blocks

packages/vue2-jest/lib/generate-code.js
No idea if this is the cleanest approach, but at least it fixes the following error for me:
```
FAIL  packages/....spec.ts
● Test suite failed to run
ReferenceError: true__options__ is not defined
```
This is caused by a missing newline before the `__options__` in the generated code.
before:
```
var staticRenderFns = []
render._withStripped = true__options__.render = render
__options__.staticRenderFns = staticRenderFns
```
with this PR:
``` 
var staticRenderFns = []
render._withStripped = true
__options__.render = render
__options__.staticRenderFns = staticRenderFns
```
For the record: this is with Vue 2.7
=> Fix "ReferenceError: true__options__ is not defined"

e2e/2.x/basic/__snapshots__/test.js.snap, packages/vue2-jest/lib/process.js
I'm using vue2-jest and code coverage is broken for a while now. I noticed a difference between `processScript` in vue2-jest vs. vue3-jest:
vue2-jest:
https://github.com/vuejs/vue-jest/blob/dbe8022c59407b7474e78d2514c317685680c15e/packages/vue2-jest/lib/process.js#L35-L53
vue3-jest:
https://github.com/vuejs/vue-jest/blob/dbe8022c59407b7474e78d2514c317685680c15e/packages/vue3-jest/lib/process.js#L30-L49
The call to `mapLines` is missing for vue2-jest.
Adding the call, I can see two differences in the tests:
- The changed snapshot in the diff. Previously the `<template>` and `<style>` block didn't show up at all in the html coverage output. Now they do.
-  Looking for example at the `e2e/2.x/basic/coverage/lcov-report/basic/components/TemplateString.vue.html` file, I see the covered lines …
=> fix: Map lines for script block

e2e/2.x/basic/components/ScriptAndScriptSetup.vue, e2e/2.x/basic/test.js, packages/vue2-jest/lib/process.js
=> fix: script and script setup in same vue component file

e2e/3.x/babel-in-package/components/Tsx.vue, e2e/3.x/babel-in-package/package.json, e2e/3.x/babel-in-package/test.js, packages/vue3-jest/lib/process.js, packages/vue3-jest/lib/transformers/typescript.js, yarn.lock
Applies the same fix that is added for Vue 2 with this PR: #395
Resolves #510
=> fix: `lang='tsx'` doesn't work for Vue 3 SFC

README.md
The key used to get config is `vue-jest` in both [`@vue/vue2-jest`](https://github.com/vuejs/vue-jest/blob/3dc76ff8491d149d89a8ba5deb02f517f1535f98/packages/vue2-jest/lib/utils.js#L57) and [`@vue/vue3-jest`](https://github.com/vuejs/vue-jest/blob/3dc76ff8491d149d89a8ba5deb02f517f1535f98/packages/vue3-jest/lib/utils.js#L57), not the respective Vue/Jest version dependent package variant name.
https://github.com/vuejs/vue-jest/blob/3dc76ff8491d149d89a8ba5deb02f517f1535f98/packages/vue2-jest/lib/utils.js#L57
https://github.com/vuejs/vue-jest/blob/3dc76ff8491d149d89a8ba5deb02f517f1535f98/packages/vue3-jest/lib/utils.js#L57
=> docs: Jest globals key is always `vue-jest`
